### ISSUE TITLE
Camera clipping plane

### ISSUE THREAD

**Issue by gitduks** [ericrosenbaum/BeetleBlocks#105]
If the geometry becomes large the camera and light setting seem to change. If you zoom out to see the entire thing the clipping planes start to have an effect. The light that travels with the camera also seems to fall off such that everything becomes dark.

I am not sure if we want to change anything as this is a very large model, but we might be able to scale the light intensity with the distance between camera and target?

http://ericrosenbaum.github.io/BeetleBlocks/beetleblocks.html#present:Username=descomp&ProjectName=dark%20spiral

**Comment by bromagosa** [comment]
IMO, the light thing is not technically a bug... pointing at an apple with a light torch is not the same as pointing at a mountain with it, so I think the code is behaving as it should.

However, clipping should not occur, that's for sure!

I'm splitting the issue in two, and adding another one to have panning speed up exponentially along with the zoom level, because when the model is large it takes forever to move around.
