### ISSUE TITLE
Same instructions that draw a square extrude a pentagon

### ISSUE THREAD

**Issue by envelupo** [ericrosenbaum/BeetleBlocks#139]
In the capture attached you can see both the pentagon and parts of the square. 

Using Firefox 37.0.2, w7-64

![beetleblocks_strangethingshappening](https://cloud.githubusercontent.com/assets/2413973/7550500/40692d28-f665-11e4-8fbd-79bc4ccfaf7f.png)

**Comment by bromagosa** [comment]
Indeed, this is a nasty bug!

Thanks for reporting it.

**Comment by bromagosa** [comment]
Just so you can work on your project in the meantime, extruding single lines does output the expected result:

![gas](https://cloud.githubusercontent.com/assets/1016697/7586188/992b014c-f8aa-11e4-8f9b-3c8e136d41ab.png)

**Comment by envelupo** [comment]
Thanks for the workaround :)

**Comment by bromagosa** [comment]
Ok, I've been investigating for hours and found out the problem is not with the ``SplineCurve3`` curve, I've rewritten the extrusion by turning it into an actual circle shape extruded along the path and I got exactly the same issues with sharp angles.

There are several possible solutions, please pick your favourite!

### Circle extrusion with 50 segments per curve:

![gas](https://cloud.githubusercontent.com/assets/1016697/7958520/86747bf8-09f0-11e5-9419-1df88a700b5f.png)
Pros: Sharp angles look better
Cons: Looks faceted. Doesn't actually look like a square.

### SplineCurve3 with lots of segments in its tube geometry
![gas](https://cloud.githubusercontent.com/assets/1016697/7958596/23e7fdba-09f1-11e5-9552-ece4f93718ce.png)
Pros: Sharp angles look better. Doesn't look faceted.
Cons: Doesn't actually look like a square.

### ClosedSplineCurve3 with reasonable amount of segments in its tube geometry
![gas](https://cloud.githubusercontent.com/assets/1016697/7958651/8af3a39c-09f1-11e5-87d5-43cc9ab34a9f.png)
Pros: All former problems solved
Cons: It's a closed shape! We'd need a different kind of extrusion mode for this.

There is another possible solution, which is to detect when a shape has been closed (end point equals start point with a threshold) and turn the Spline3 into a ClosedSpline3. That, though, would mean we'd need to think about what to do with future points added to the extrusion path...

**Comment by bromagosa** [comment]
Let's do tube → sphere → tube

**Comment by bromagosa** [comment]
This has been fixed, and all examples tested to work with no problem except for when there are A LOT of extrusion points, like in the snail example, which now looks a bit uglier and makes BeetleBlocks quite slower in my PC:

![image](https://cloud.githubusercontent.com/assets/1016697/8064675/79a1375e-0edc-11e5-9771-c67dc5be0274.png)

Still, everything should now be printable, which I think was the priority.

BTW, I've used cylinder geometries because they're native to three.js and look smoother than extrusions.

Let's now think of ways of speeding this up! :)
